# Generated by Django 4.2.6 on 2023-10-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_libro', models.CharField(max_length=50)),
                ('autor_libro', models.TextField()),
                ('paginas_libro', models.IntegerField()),
                ('editorial_libro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pelicula', models.CharField(max_length=50)),
                ('tipo_pelicula', models.TextField()),
                ('duracion_pelicula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_serie', models.CharField(max_length=50)),
                ('tipo_serie', models.TextField()),
                ('capitulos_serie', models.IntegerField()),
                ('duracion_capitulos', models.IntegerField()),
            ],
        ),
    ]
