# Generated by Django 4.2.6 on 2023-11-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_libro_pelicula_serie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paleta',
        ),
    ]
