# Generated by Django 4.2.6 on 2023-11-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anime', models.CharField(max_length=50)),
                ('capitulos_anime', models.IntegerField()),
                ('inicio_anime', models.DateField()),
            ],
        ),
    ]
