# Generated by Django 4.2.6 on 2023-11-18 01:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_datosextra_avatar_alter_datosextra_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosextra',
            name='biografia',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
