# Generated by Django 4.2.6 on 2023-11-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_datosextra_biografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosextra',
            name='biografia',
        ),
    ]
