# Generated by Django 4.2.6 on 2023-11-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_manga', models.CharField(max_length=50)),
                ('tomos_manga', models.IntegerField()),
                ('genero_manga', models.CharField(max_length=15)),
            ],
        ),
    ]
